[package]
name = "fift"
description = "Rust implementation of the Fift esoteric language"
repository = "https://github.com/broxus/fift"
version = "0.1.16"
edition = "2021"
rust-version = "1.70"
include = ["src/**/*.rs", "src/**/*.fif", "LICENSE-*", "README.md"]
license = "MIT OR Apache-2.0"

[lib]
name = "fift"

[workspace]
members = ["proc", "cli", "libs"]

[dependencies]
ahash = "0.8"
anyhow = "1.0"
base64 = "0.21"
crc = "3.0"
dyn-clone = "1.0"
everscale-crypto = "0.2"
hex = "0.4"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
rand = "0.8"
sha2 = "0.10"
thiserror = "1.0"
unicode-segmentation = "1.0"

everscale-types = "0.1.0-rc.3"

fift-proc = { path = "./proc", version = "=0.1.15" }
