[package]
name = "fift"
description = "Rust implementation of the Fift esoteric language"
repository = "https://github.com/broxus/fift"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
include = ["src/**/*.rs", "LICENSE-*", "README.md"]
license = "MIT OR Apache-2.0"

[workspace]
members = ["proc"]

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
thiserror = "1.0"
hex = "0.4"
dyn-clone = "1.0"
unicode-segmentation = "1.0"

#everscale-types = "0.1.0-rc.0"
everscale-types = { git = "https://github.com/broxus/everscale-types.git" }

fift-proc = { path = "./proc" }
